In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import lightgbm as lg

In [2]:
# Reading the Dataset
dataset = pd.read_csv("Preprocessed_project_risk.csv")
dataset

Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
0          32.0         1526276.550                       32.0   
1           2.0          390790.150                        9.0   
2           2.0          246674.760                        6.0   
3          12.0         1427830.630                       17.0   
4          24.0         1696746.640                       24.0   
...         ...                 ...                        ...   
3995        9.0          731548.970                       14.0   
3996        9.0          492981.400                        9.0   
3997       12.0         1097040.650                       24.0   
3998       26.0         2650876.115                       28.0   
3999       33.0         1627904.310                       28.0   

      Complexity_Score  Stakeholder_Count  Past_Similar_Projects  \
0                 9.70               16.0                    3.0   
1                 2.72                9.0                    0.0   
2                 2.04                7.0                    1.0   
3                 7.54               16.0                    0.0   
4                 6.68               17.0                    0.0   
...                ...                ...                    ...   
3995              5.40                9.0                    4.0   
3996              2.69                8.0                    5.0   
3997              8.82               10.0                    2.0   
3998             10.00               23.0                    1.0   
3999              7.04               15.0                    1.0   

      External_Dependencies_Count  Change_Request_Frequency  \
0                             3.0                      1.05   
1                             2.0                      2.61   
2                             0.0                      0.83   
3                             5.0                      2.42   
4                             2.0                      0.16   
...                           ...                       ...   
3995                          3.0                      1.09   
3996                          3.0                      2.11   
3997                          4.0                      0.52   
3998                          6.0                      1.19   
3999                          3.0                      1.56   

      Team_Turnover_Rate  Vendor_Reliability_Score  ...  \
0                   0.16                      0.84  ...   
1                   0.42                      0.79  ...   
2                   0.55                      0.89  ...   
3                   0.33                      0.84  ...   
4                   0.36                      0.86  ...   
...                  ...                       ...  ...   
3995                0.25                      0.94  ...   
3996                0.06                      0.71  ...   
3997                0.23                      0.95  ...   
3998                0.30                      0.50  ...   
3999                0.25                      0.78  ...   

      Tech_Environment_Stability  Contract_Type  Resource_Contention_Level  \
0                              0              3                          0   
1                              0              0                          1   
2                              0              0                          0   
3                              2              2                          0   
4                              0              0                          0   
...                          ...            ...                        ...   
3995                           1              1                          2   
3996                           0              1                          2   
3997                           1              3                          1   
3998                           0              1                          2   
3999                           0              2                         

In [3]:
# Separate target first
dependent = dataset["Risk_Level"]
independent = dataset.drop(columns=["Risk_Level"])

# Apply get_dummies only on independent
X_encoded = pd.get_dummies(independent, drop_first=True)
X_encoded=X_encoded.replace({True:1,False:0})
#from sklearn.preprocessing import LabelEncoder

#le = LabelEncoder()
#Y_encoded = le.fit_transform(dependent)
print(X_encoded.shape)
print(dependent.shape)

(4000, 50)
(4000,)


In [65]:
from sklearn.feature_selection import SelectKBest, f_classif

selector = SelectKBest(score_func=f_classif, k=40)
X_anova = selector.fit_transform(X_encoded, dependent)

selected_features = X_encoded.columns[selector.get_support()]
X_selected = X_encoded[selected_features]
X_selected

C:\Anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [24] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
C:\Anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw


Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
0          32.0         1526276.550                       32.0   
1           2.0          390790.150                        9.0   
2           2.0          246674.760                        6.0   
3          12.0         1427830.630                       17.0   
4          24.0         1696746.640                       24.0   
...         ...                 ...                        ...   
3995        9.0          731548.970                       14.0   
3996        9.0          492981.400                        9.0   
3997       12.0         1097040.650                       24.0   
3998       26.0         2650876.115                       28.0   
3999       33.0         1627904.310                       28.0   

      Complexity_Score  Stakeholder_Count  Past_Similar_Projects  \
0                 9.70               16.0                    3.0   
1                 2.72                9.0                    0.0   
2                 2.04                7.0                    1.0   
3                 7.54               16.0                    0.0   
4                 6.68               17.0                    0.0   
...                ...                ...                    ...   
3995              5.40                9.0                    4.0   
3996              2.69                8.0                    5.0   
3997              8.82               10.0                    2.0   
3998             10.00               23.0                    1.0   
3999              7.04               15.0                    1.0   

      External_Dependencies_Count  Team_Turnover_Rate  \
0                             3.0                0.16   
1                             2.0                0.42   
2                             0.0                0.55   
3                             5.0                0.33   
4                             2.0                0.36   
...                           ...                 ...   
3995                          3.0                0.25   
3996                          3.0                0.06   
3997                          4.0                0.23   
3998                          6.0                0.30   
3999                          3.0                0.25   

      Vendor_Reliability_Score  Communication_Frequency  ...  \
0                         0.84                     1.90  ...   
1                         0.79                     2.65  ...   
2                         0.89                     1.87  ...   
3                         0.84                     1.36  ...   
4                         0.86                     1.02  ...   
...                        ...                      ...  ...   
3995                      0.94                     1.26  ...   
3996                      0.71                     4.34  ...   
3997                      0.95                     4.70  ...   
3998                      0.50                     5.59  ...   
3999                      0.78                     4.28  ...   

      Org_Process_Maturity  Data_Security_Requirements  \
0                        2                           2   
1                        3                           1   
2                        0                           2   
3                        2                           3   
4                        1                           2   
...                    ...                         ...   
3995                     0                           0   
3996                     1                           3   
3997                     0                           0   
3998                     1                           0   
3999                     2                           3   

      Key_Stakeholder_Availability  Tech_Environment_Stability  \
0                                2                           0   
1                                0                           0   
2                                3             

In [66]:
dependent

0         High
1          Low
2       Medium
3         High
4         High
         ...  
3995      High
3996    Medium
3997      High
3998      High
3999    Medium
Name: Risk_Level, Length: 4000, dtype: object

In [67]:
corr_matrix=X_encoded.corr()
corr_matrix

Team_Size  Project_Budget_USD  \
Team_Size                         1.000000            0.885798   
Project_Budget_USD                0.885798            1.000000   
Estimated_Timeline_Months         0.864391            0.864842   
Complexity_Score                  0.478861            0.587870   
Stakeholder_Count                 0.785608            0.886197   
Past_Similar_Projects            -0.006827           -0.002166   
External_Dependencies_Count       0.334217            0.409297   
Change_Request_Frequency          0.018489            0.012245   
Team_Turnover_Rate                0.014237            0.023810   
Vendor_Reliability_Score         -0.018919           -0.022124   
Historical_Risk_Incidents        -0.003845           -0.010114   
Communication_Frequency          -0.006224           -0.008363   
Geographical_Distribution        -0.005905           -0.001846   
Schedule_Pressure                -0.463054           -0.413624   
Budget_Utilization_Rate           0.007597           -0.001147   
Market_Volatility                -0.011013           -0.009748   
Integration_Complexity            0.001621           -0.002298   
Resource_Availability             0.007460            0.000850   
Organizational_Change_Frequency   0.000545           -0.003105   
Cross_Functional_Dependencies     0.016187            0.021158   
Previous_Delivery_Success_Rate   -0.034336           -0.032661   
Technical_Debt_Level             -0.327301           -0.254306   
Project_Start_Month              -0.018499           -0.019154   
Current_Phase_Duration_Months     0.499923            0.503067   
Seasonal_Risk_Factor                   NaN                 NaN   
Project_ID                        0.002671            0.002456   
Project_Type                     -0.271421           -0.056618   
Methodology_Used                  0.284604            0.102203   
Team_Experience_Level            -0.014552           -0.012795   
Project_Phase                    -0.004421           -0.002612   
Requirement_Stability            -0.013219           -0.023605   
Regulatory_Compliance_Level      -0.012507           -0.012455   
Technology_Familiarity            0.059560            0.128143   
Stakeholder_Engagement_Level     -0.011994           -0.013098   
Executive_Sponsorship             0.008842            0.013872   
Funding_Source                   -0.017884           -0.017897   
Priority_Level                    0.005506            0.006826   
Project_Manager_Experience        0.000696            0.004158   
Org_Process_Maturity             -0.105320           -0.107014   
Data_Security_Requirements       -0.032728           -0.025782   
Key_Stakeholder_Availability     -0.017918           -0.019448   
Tech_Environment_Stability       -0.384641           -0.312069   
Contract_Type                     0.007465           -0.001072   
Resource_Contention_Level        -0.091706           -0.078846   
Industry_Volatility              -0.191828           -0.239588   
Client_Experience_Level           0.256410            0.405942   
Change_Control_Maturity          -0.019352           -0.011405   
Risk_Management_Maturity         -0.043273           -0.040958   
Team_Colocation                  -0.002134            0.013866   
Documentation_Quality            -0.005299           -0.004091   

                                 Estimated_Timeline_Months  Complexity_Score  \
Team_Size                                         0.864391          0.478861   
Project_Budget_USD                                0.864842          0.587870   
Estimated_Timeline_Months                         1.000000          0.792578   
Complexity_Score                                  0.792578          1.000000   
Stakeholder_Count                                 0.770566          0.524190   
Past_Similar_Projects                            -0.001003          0.009751   
External_Dependencies_Count                       0.553153          0.704350   
Change_Request_Frequency  

In [68]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_selected, dependent, test_size = 1/3, random_state =42)
X_train, X_test, Y_train, Y_test

(      Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
 1251       35.0          2360835.01                       25.0   
 365        18.0          1814824.23                       23.0   
 1366       22.0           772811.99                       21.0   
 276        18.0          1495394.30                       23.0   
 2639        6.0           613149.17                        8.0   
 ...         ...                 ...                        ...   
 1130        8.0           411443.47                        8.0   
 1294       10.0           545103.53                       14.0   
 860        14.0          1115158.11                       17.0   
 3507       28.0          1772601.08                       17.0   
 3174        9.0           588795.51                       11.0   
 
       Complexity_Score  Stakeholder_Count  Past_Similar_Projects  \
 1251              5.84               17.0                    5.0   
 365               8.56               17.0              

In [76]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [77]:
from lightgbm  import LGBMClassifier
from sklearn.model_selection import GridSearchCV

param_dist = {
    'boosting_type ':['gbdt'],
    'n_estimators': [100, 500, 1000],
    'num_leaves': [31, 60, 100],
    'learning_rate': [0.01, 0.1],
    'feature_fraction': [0.7, 0.9]
}
grid = GridSearchCV(LGBMClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
   
# fitting the model for grid search 
grid.fit(X_train, Y_train) 

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[LightGBM] [Warning] Unknown parameter: criterion
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Warning] Unknown parameter: criterion
[LightGBM] [Warning] Unknown parameter: max_features
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.002267 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2061
[LightGBM] [Info] Number of data points in the train set: 2666, number of used features: 40
[LightGBM] [Info] Start training from score -1.710390
[LightGBM] [Info] Start training from score -1.309083
[LightGBM] [Info] Start training from score -1.602336
[LightGBM] [Info] Start training from score -1.056381


GridSearchCV(estimator=LGBMClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1_weighted', verbose=3)

In [78]:
# print best parameter after tuning 
print(grid.best_params_) 
result=grid.cv_results_
print(result)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, grid_predictions)

{'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}
{'mean_fit_time': array([ 3.23710694, 26.21880221,  2.93971205, 24.65535684,  2.55804939,
       24.52701654,  2.71697669, 21.40157847,  2.69954362, 18.12338266,
        2.24168234, 11.776898  ]), 'std_fit_time': array([0.15097768, 2.39470659, 0.07586157, 0.20420617, 0.239213  ,
       1.697937  , 0.05830859, 0.29666984, 0.18672646, 1.96765372,
       0.2504424 , 0.24781279]), 'mean_score_time': array([0.02546434, 0.04052482, 0.02910671, 0.03401008, 0.02290106,
       0.02559366, 0.02507143, 0.02738881, 0.02470312, 0.02509704,
       0.01916223, 0.03565397]), 'std_score_time': array([0.00620352, 0.0066248 , 0.00888993, 0.0054568 , 0.00181827,
       0.00415328, 0.00638818, 0.00526519, 0.00148375, 0.0034108 ,
       0.00361526, 0.01379914]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'en

In [79]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'n_estimators': 100}: 0.5963939786679721


In [80]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[154  98   2  26]
 [ 33 150   3 130]
 [  1   5 167  96]
 [  5  87  57 320]]


In [81]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

    Critical       0.80      0.55      0.65       280
        High       0.44      0.47      0.46       316
         Low       0.73      0.62      0.67       269
      Medium       0.56      0.68      0.61       469

    accuracy                           0.59      1334
   macro avg       0.63      0.58      0.60      1334
weighted avg       0.62      0.59      0.60      1334



In [82]:
from sklearn.metrics import roc_auc_score

y_prob = grid.predict_proba(X_test)

roc_auc = roc_auc_score(
    Y_test,
    y_prob,
    multi_class="ovo",   # or "ovr"
    average="weighted"
)

print("ROC AUC:", roc_auc)



[LightGBM] [Warning] Unknown parameter: criterion
[LightGBM] [Warning] Unknown parameter: max_features
ROC AUC: 0.8393180585391949


In [52]:
best_model = grid.best_estimator_
importance_of_each_feature=best_model.feature_importances_
importance_of_each_feature

array([218, 314, 197, 670, 152, 146, 147, 583, 397, 566, 145, 174, 494,
       559, 590, 536, 480, 246, 621, 186, 167,  79, 221, 320, 210, 175,
       341, 329, 192, 234, 362, 197, 379, 175, 204, 157, 257, 219, 225,
       136])

In [53]:
X_selected.columns

Index(['Team_Size', 'Project_Budget_USD', 'Estimated_Timeline_Months',
       'Complexity_Score', 'Stakeholder_Count', 'Past_Similar_Projects',
       'External_Dependencies_Count', 'Team_Turnover_Rate',
       'Vendor_Reliability_Score', 'Communication_Frequency',
       'Geographical_Distribution', 'Schedule_Pressure',
       'Budget_Utilization_Rate', 'Market_Volatility',
       'Integration_Complexity', 'Resource_Availability',
       'Organizational_Change_Frequency', 'Cross_Functional_Dependencies',
       'Previous_Delivery_Success_Rate', 'Technical_Debt_Level',
       'Current_Phase_Duration_Months', 'Project_Type',
       'Team_Experience_Level', 'Project_Phase', 'Requirement_Stability',
       'Regulatory_Compliance_Level', 'Technology_Familiarity',
       'Stakeholder_Engagement_Level', 'Executive_Sponsorship',
       'Project_Manager_Experience', 'Org_Process_Maturity',
       'Data_Security_Requirements', 'Key_Stakeholder_Availability',
       'Tech_Environment_Stability',