In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import lightgbm as lg

In [2]:
# Reading the Dataset
dataset = pd.read_csv(r"D:\AI course Tamil\CapstoneProject\2.Data Preprocessing\Preprocessed_project_risk.csv")
dataset

Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
0          32.0         1526276.550                       32.0   
1           2.0          390790.150                        9.0   
2           2.0          246674.760                        6.0   
3          12.0         1427830.630                       17.0   
4          24.0         1696746.640                       24.0   
...         ...                 ...                        ...   
3995        9.0          731548.970                       14.0   
3996        9.0          492981.400                        9.0   
3997       12.0         1097040.650                       24.0   
3998       26.0         2650876.115                       28.0   
3999       33.0         1627904.310                       28.0   

      Complexity_Score  Stakeholder_Count  Past_Similar_Projects  \
0                 9.70               16.0                    3.0   
1                 2.72                9.0                    0.0   
2                 2.04                7.0                    1.0   
3                 7.54               16.0                    0.0   
4                 6.68               17.0                    0.0   
...                ...                ...                    ...   
3995              5.40                9.0                    4.0   
3996              2.69                8.0                    5.0   
3997              8.82               10.0                    2.0   
3998             10.00               23.0                    1.0   
3999              7.04               15.0                    1.0   

      External_Dependencies_Count  Change_Request_Frequency  \
0                             3.0                      1.05   
1                             2.0                      2.61   
2                             0.0                      0.83   
3                             5.0                      2.42   
4                             2.0                      0.16   
...                           ...                       ...   
3995                          3.0                      1.09   
3996                          3.0                      2.11   
3997                          4.0                      0.52   
3998                          6.0                      1.19   
3999                          3.0                      1.56   

      Team_Turnover_Rate  Vendor_Reliability_Score  ...  \
0                   0.16                      0.84  ...   
1                   0.42                      0.79  ...   
2                   0.55                      0.89  ...   
3                   0.33                      0.84  ...   
4                   0.36                      0.86  ...   
...                  ...                       ...  ...   
3995                0.25                      0.94  ...   
3996                0.06                      0.71  ...   
3997                0.23                      0.95  ...   
3998                0.30                      0.50  ...   
3999                0.25                      0.78  ...   

      Tech_Environment_Stability  Contract_Type  Resource_Contention_Level  \
0                              0              3                          0   
1                              0              0                          1   
2                              0              0                          0   
3                              2              2                          0   
4                              0              0                          0   
...                          ...            ...                        ...   
3995                           1              1                          2   
3996                           0              1                          2   
3997                           1              3                          1   
3998                           0              1                          2   
3999                           0              2                         

In [3]:
# Separate target first
dependent = dataset["Risk_Level"]
independent = dataset.drop(columns=["Risk_Level"])

# Apply get_dummies only on independent
X_encoded = pd.get_dummies(independent, drop_first=True)
X_encoded=X_encoded.replace({True:1,False:0})
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y_encoded = le.fit_transform(dependent)
print(X_encoded.shape)
print(Y_encoded.shape)

(4000, 50)
(4000,)


In [4]:
X_encoded

Team_Size  Project_Budget_USD  Estimated_Timeline_Months  \
0          32.0         1526276.550                       32.0   
1           2.0          390790.150                        9.0   
2           2.0          246674.760                        6.0   
3          12.0         1427830.630                       17.0   
4          24.0         1696746.640                       24.0   
...         ...                 ...                        ...   
3995        9.0          731548.970                       14.0   
3996        9.0          492981.400                        9.0   
3997       12.0         1097040.650                       24.0   
3998       26.0         2650876.115                       28.0   
3999       33.0         1627904.310                       28.0   

      Complexity_Score  Stakeholder_Count  Past_Similar_Projects  \
0                 9.70               16.0                    3.0   
1                 2.72                9.0                    0.0   
2                 2.04                7.0                    1.0   
3                 7.54               16.0                    0.0   
4                 6.68               17.0                    0.0   
...                ...                ...                    ...   
3995              5.40                9.0                    4.0   
3996              2.69                8.0                    5.0   
3997              8.82               10.0                    2.0   
3998             10.00               23.0                    1.0   
3999              7.04               15.0                    1.0   

      External_Dependencies_Count  Change_Request_Frequency  \
0                             3.0                      1.05   
1                             2.0                      2.61   
2                             0.0                      0.83   
3                             5.0                      2.42   
4                             2.0                      0.16   
...                           ...                       ...   
3995                          3.0                      1.09   
3996                          3.0                      2.11   
3997                          4.0                      0.52   
3998                          6.0                      1.19   
3999                          3.0                      1.56   

      Team_Turnover_Rate  Vendor_Reliability_Score  ...  \
0                   0.16                      0.84  ...   
1                   0.42                      0.79  ...   
2                   0.55                      0.89  ...   
3                   0.33                      0.84  ...   
4                   0.36                      0.86  ...   
...                  ...                       ...  ...   
3995                0.25                      0.94  ...   
3996                0.06                      0.71  ...   
3997                0.23                      0.95  ...   
3998                0.30                      0.50  ...   
3999                0.25                      0.78  ...   

      Key_Stakeholder_Availability  Tech_Environment_Stability  Contract_Type  \
0                                2                           0              3   
1                                0                           0              0   
2                                3                           0              0   
3                                1                           2              2   
4                                3                           0              0   
...                            ...                         ...            ...   
3995                             3                           1              1   
3996                             2                           0              1   
3997                             3                           1              3   
3998                             3                           0              1   
3999                             3     

In [5]:
Y_encoded

array([1, 2, 3, ..., 1, 1, 3])

In [6]:
corr_matrix=X_encoded.corr()
corr_matrix

Team_Size  Project_Budget_USD  \
Team_Size                         1.000000            0.885798   
Project_Budget_USD                0.885798            1.000000   
Estimated_Timeline_Months         0.864391            0.864842   
Complexity_Score                  0.478861            0.587870   
Stakeholder_Count                 0.785608            0.886197   
Past_Similar_Projects            -0.006827           -0.002166   
External_Dependencies_Count       0.334217            0.409297   
Change_Request_Frequency          0.018489            0.012245   
Team_Turnover_Rate                0.014237            0.023810   
Vendor_Reliability_Score         -0.018919           -0.022124   
Historical_Risk_Incidents        -0.003845           -0.010114   
Communication_Frequency          -0.006224           -0.008363   
Geographical_Distribution        -0.005905           -0.001846   
Schedule_Pressure                -0.463054           -0.413624   
Budget_Utilization_Rate           0.007597           -0.001147   
Market_Volatility                -0.011013           -0.009748   
Integration_Complexity            0.001621           -0.002298   
Resource_Availability             0.007460            0.000850   
Organizational_Change_Frequency   0.000545           -0.003105   
Cross_Functional_Dependencies     0.016187            0.021158   
Previous_Delivery_Success_Rate   -0.034336           -0.032661   
Technical_Debt_Level             -0.327301           -0.254306   
Project_Start_Month              -0.018499           -0.019154   
Current_Phase_Duration_Months     0.499923            0.503067   
Seasonal_Risk_Factor                   NaN                 NaN   
Project_ID                        0.002671            0.002456   
Project_Type                     -0.271421           -0.056618   
Methodology_Used                  0.284604            0.102203   
Team_Experience_Level            -0.014552           -0.012795   
Project_Phase                    -0.004421           -0.002612   
Requirement_Stability            -0.013219           -0.023605   
Regulatory_Compliance_Level      -0.012507           -0.012455   
Technology_Familiarity            0.059560            0.128143   
Stakeholder_Engagement_Level     -0.011994           -0.013098   
Executive_Sponsorship             0.008842            0.013872   
Funding_Source                   -0.017884           -0.017897   
Priority_Level                    0.005506            0.006826   
Project_Manager_Experience        0.000696            0.004158   
Org_Process_Maturity             -0.105320           -0.107014   
Data_Security_Requirements       -0.032728           -0.025782   
Key_Stakeholder_Availability     -0.017918           -0.019448   
Tech_Environment_Stability       -0.384641           -0.312069   
Contract_Type                     0.007465           -0.001072   
Resource_Contention_Level        -0.091706           -0.078846   
Industry_Volatility              -0.191828           -0.239588   
Client_Experience_Level           0.256410            0.405942   
Change_Control_Maturity          -0.019352           -0.011405   
Risk_Management_Maturity         -0.043273           -0.040958   
Team_Colocation                  -0.002134            0.013866   
Documentation_Quality            -0.005299           -0.004091   

                                 Estimated_Timeline_Months  Complexity_Score  \
Team_Size                                         0.864391          0.478861   
Project_Budget_USD                                0.864842          0.587870   
Estimated_Timeline_Months                         1.000000          0.792578   
Complexity_Score                                  0.792578          1.000000   
Stakeholder_Count                                 0.770566          0.524190   
Past_Similar_Projects                            -0.001003          0.009751   
External_Dependencies_Count                       0.553153          0.704350   
Change_Request_Frequency  

In [7]:
from sklearn.feature_selection import VarianceThreshold
var_selector = VarianceThreshold(threshold=0.01)
X_var = var_selector.fit_transform(X_encoded)

X_var_columns = X_encoded.columns[var_selector.get_support()]

In [8]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_var, dependent, test_size = 1/3, random_state =42)
X_train, X_test, Y_train, Y_test

(array([[3.50000000e+01, 2.36083501e+06, 2.50000000e+01, ...,
         1.00000000e+00, 0.00000000e+00, 2.00000000e+00],
        [1.80000000e+01, 1.81482423e+06, 2.30000000e+01, ...,
         3.00000000e+00, 3.00000000e+00, 0.00000000e+00],
        [2.20000000e+01, 7.72811990e+05, 2.10000000e+01, ...,
         2.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        ...,
        [1.40000000e+01, 1.11515811e+06, 1.70000000e+01, ...,
         3.00000000e+00, 2.00000000e+00, 0.00000000e+00],
        [2.80000000e+01, 1.77260108e+06, 1.70000000e+01, ...,
         3.00000000e+00, 2.00000000e+00, 2.00000000e+00],
        [9.00000000e+00, 5.88795510e+05, 1.10000000e+01, ...,
         2.00000000e+00, 2.00000000e+00, 2.00000000e+00]]),
 array([[5.00000000e+00, 7.40575900e+05, 9.00000000e+00, ...,
         2.00000000e+00, 3.00000000e+00, 2.00000000e+00],
        [3.00000000e+00, 4.38240880e+05, 9.00000000e+00, ...,
         3.00000000e+00, 2.00000000e+00, 1.00000000e+00],
        [3.00000000e+00, 

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Applying PCA
from sklearn.decomposition import PCA
pca = PCA(n_components = 2)
X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_

In [11]:
from lightgbm  import LGBMClassifier
classifier=LGBMClassifier()
classifier.fit(X_train,Y_train)
classifier

C:\Anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "C:\Anaconda3\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000592 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 2666, number of used features: 2
[LightGBM] [Info] Start training from score -1.710390
[LightGBM] [Info] Start training from score -1.309083
[LightGBM] [Info] Start training from score -1.602336
[LightGBM] [Info] Start training from score -1.056381


LGBMClassifier()

In [12]:
y_pred=classifier.predict(X_test)
y_pred

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, y_pred)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(Y_test, y_pred)

In [13]:
from sklearn.metrics import f1_score
f1_macro=f1_score(Y_test,y_pred,average='weighted')
print("The f1_macro value for best parameter {}:".format(classifier),f1_macro)

The f1_macro value for best parameter LGBMClassifier(): 0.2977214460999602


In [14]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[ 71  87  19 103]
 [ 45  73  52 146]
 [ 21  50  42 156]
 [ 54 106  85 224]]


In [15]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

    Critical       0.37      0.25      0.30       280
        High       0.23      0.23      0.23       316
         Low       0.21      0.16      0.18       269
      Medium       0.36      0.48      0.41       469

    accuracy                           0.31      1334
   macro avg       0.29      0.28      0.28      1334
weighted avg       0.30      0.31      0.30      1334



In [16]:
from sklearn.metrics import roc_auc_score

y_prob = classifier.predict_proba(X_test)

roc_auc = roc_auc_score(Y_test,y_prob,   multi_class="ovo",   # or "ovr"   
                        average="weighted")

print("ROC AUC:", roc_auc)



ROC AUC: 0.5550145912447172
